"""remove_callback_url

Revision ID: 0749dce46697
Revises: 61429c72a7bf
Create Date: 2020-11-04 21:44:39.799124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0749dce46697'
down_revision = '61429c72a7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelinerun', 'callback_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelinerun', sa.Column('callback_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
